#!/bin/bash

# Stop on errors
set -Eeuo pipefail

# Usage
if [ "$#" != 1 ]; then
  echo "Usage: $0 DIR"
  exit 1
fi

if [ -d "$1" ]; then
  # Argument is a directory
  SOLUTION="$1"
else
    # Invalid argument
    echo "Invalid argument: $1"
    exit 1
fi

# Print commands
set -x

# Install dependencies
npm ci --prefix "$SOLUTION"
